apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpj-ms1signup-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms1signup
  template:
    metadata:
      labels:
        app: ms1signup
    spec:
      nodeSelector:
        role: microservice1
      containers:
      - name: ms1signup
        image: djtoler/fpj_microservice1signup:latest
        ports:
        - containerPort: 8001