apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpj-ms2login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms2login
  template:
    metadata:
      labels:
        app: ms2login
    spec:
      nodeSelector:
        role: microservice2
      containers:
      - name: ms2login
        image: djtoler/fpj_microservice2login:latest
        ports:
        - containerPort: 8002